### ISSUE TITLE
Move some pipemenu functions to bl-include.cfg?

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-pipemenus#12]
The graphics and browser pipemenus both use an  app/browserExists() function, and several other pipemenus I am working on also use this. There are also the sections involving setupFunctionName and promptInstall which are duplicated many times.

Is it worth making functions in bl-include.cfg to save multiple instances of the same code? It would be more elegant, but is it worth the effort?

**Comment by ghost** [comment]
If it's re-usable, then the function can be put in the library. If it's not, it doesn't belong in a library -> seems reasonable to me.

**Comment by johnraff** [comment]
For example, browserExists(), screenshooterExists could be replaced by appExists(), slightly rewritten to allow different arrays to be accessed. Such an appExists() might be re-usable in a different part of the forest.

BTW is .cfg really a suitable file ending for a collection of shell functions?

**Comment by capn-damo** [comment]
"It would be more elegant, but is it worth the effort?"

Yes it would be better to have library functions, but since it doesn't affect anything atm is it worth the effort of re-writing scripts at this stage? It could be left for BL Deuterium (aka BL Hydrogen 1.1  )

**Comment by johnraff** [comment]
^true. There's plenty of stuff to sort out as it is.

**Comment by ghost** [comment]
^ Agreed. So I suggest to keep things private that don't need to be public :D

**Comment by AlexDaniel** [comment]
What do you mean by private? Just use another branch, perhaps?

**Comment by ghost** [comment]
Not in a library but in the files. No library. Like functions declared static in C. A bit unlucky choice of words on my side.
