### ISSUE TITLE
bl-x-www-browser-pipemenu has references to packages.crunchbang

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-pipemenus#20]
...for the Opera and google-chrome apt-keys

**Comment by johnraff** [comment]
Ah indeed. They're just a backup but could be removed I guess. Maybe we could put copies of those keys somewhere in bunsenland? They might change in the future though.

**Comment by ghost** [comment]
How about we remove these entries? It's not like they go anywhere or are indiscoverable on the internet if needed.

**Comment by johnraff** [comment]
Agreed. Will do tomorrow.

...done.
