### ISSUE TITLE
bl-places-pipemenu and bl- alternatives

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-pipemenus#21]
Ref bl- alternatives, lines 32/33:

`# Default command to open files with - others might be xdg-open, gnome-open, thunar, #pcmanfm...`
`default_open_cmd=xdg-open  # exo-open comes with thunar`

Keep `xdg-open` I guess?

...and should those commands be quoted? eg
`text_editor='bl-text-editor'`

**Comment by johnraff** [comment]
bl-alternatives You mean bl-places-pipemenu here? Yes, let's keep xdg-open - it looks like the most generic option.

There's no need to quote commands if they're a single word. I don't think it hurts though.
