### ISSUE TITLE
Package not found: Google chrome stable

### ISSUE THREAD

**Issue by mrwm** [BunsenLabs/bunsen-pipemenus#29]
The terminal throws an error when I tried installing google chrome. Apparently, it's not adding the chrome repo in sources.list

**Comment by wiiliam** [comment]
Is there a place where I can edit the pipe menu xml's?

**Comment by ghost** [comment]
Debian Jessie is shipping chromium, the FOSS build of the Chromium project, you can temporarily install that.

@BunsenLabs/config-team @johnraff bl-x-www-browser-pipemenu contains for setting up google-chrome. Has this been tested recently?

**Comment by johnraff** [comment]
This was my fault. At some point a change I made in the method of passing the setupFunction from bl-x-www-browser-pipemenu to /usr/lib/bunsen/bunsen-common/bl-include.cfg failed to be merged into the git file. 

I have tested the current script and believe this is now fixed. 
You can run `~/.bunsen-netinstall-logs/upgrade-bunsen-pkgs --upgrade` to pull in the new version.
Please reopen if the issue persists.
