### ISSUE TITLE
"Recent Files" pipemenu nil value error and "Clear Recent Files" not working.

### ISSUE THREAD

**Issue by smacz42** [BunsenLabs/bunsen-pipemenus#30]
In a fresh install from a Jessie netinstall and the bunsen-netinstall setup, I recieved this error while hovering over "Recent Files" in the OB root menu.

```
Invalid output from pipe-menu "bl-recent-files-pipemenu -rl15"
```

I opened then closed a file from the command line (vim) and tried it again. Same gtk popup with the same error. I opened then closed a file using thunar in geany and tried it again. The gtk popup was gone and the file I had opened was listed in the menu in the space under "Clear recent files".

The output from executing `/usr/bin/bl-recent-files-pipemenu` (without having a `~/.local/share/recently-used.xbel` file) from the command line is as follows:

```
lua 5.2: /usr/bin/bl-recent-files-pipemenu:125: attempt to concatenate local 'path' (a nil value)
stack traceback
    /usr/bin/bl-recent-files-pipemenu:125: in function 'add_remove_file_item'
    /usr/bin/bl-recent-files-pipemenu:198: in function 'main'
    /usr/bin/bl-recent-files-pipemenu:213: in main chunk
    [C]: in ?
```

_BUT_ after `$ touch ~/.local/share/recently-used.xbel` the output reacts as expected; aka not listing any recent files, but displaying only a single entry of "Clear recent files". I would assume that this file would need to be placed in the netinstall script in order for this functionality to occur OOTB.

As somewhat of a sidenote, when attempting to revert back to the state without any cached recent files I had selected "Clear recent files", it did nothing. The files still existed in the menu. This was repeated after opening several files via thunar/geany, and then closing them. There were then several files in the "Recent Files" pipemenu, and after hitting "Clear recent files" and rechecking, they were still there.

There was no error given, but the files were still listed as recent files.

**Comment by johnraff** [comment]
Confirmed - same behaviour here.

**Comment by ghost** [comment]
@johnraff, could you test this change (I'm still not using openbox).

**Comment by johnraff** [comment]
The error message no longer appears when there is no ~/.local/share/recently-used.xbel file, it is replaced by a nice-looking "no recent files" popup.

However, the "Clear recent files" menu item still fails to work, and it has reverted to its former position at the bottom of the list, rather than the preferred place at the top.

**Comment by ghost** [comment]
Strange. For me , the clear recent files stuff appears at the top of the menu, regardless of how many files are in the list. I can't reproduce the bottom-located entry.

``` xml
<openbox_pipe_menu>
  <item label='Clear recent files'>
    <command>&quot;/bin/bash&quot; &quot;-c &apos;&gt; /home/joj/.local/share/recently-used.xbel&apos;&quot;</command>
  </item>
  <separator/>
  <item label='lua-anidb-git-r81.e3225d8-1.src.tar.gz'>
    <action name='Execute'>
      <command>&quot;firefox&quot; &quot;file:///tmp/foo/_/lua-anidb-git/lua-anidb-git-r81.e3225d8-1.src.tar.gz&quot;</command>
    </action>
  </item>
  <item label='lua-anidb-git-r94.0579a23-1.src.tar.gz'>
    <action name='Execute'>
      <command>&quot;firefox&quot; &quot;file:///tmp/foo/_/lua-anidb-git/lua-anidb-git-r94.0579a23-1.src.tar.gz&quot;</command>
    </action>
  </item>
  <item label='filp2014__eng-1.pdf'>
    <action name='Execute'>
      <command>&quot;firefox&quot; &quot;file:///tmp/filp2014_eng-1.pdf&quot;</command>
    </action>
  </item>
</openbox_pipe_menu>
```

Does running the menu script stand-alone give you the same output? Could it be that openbox re-sorts the menu alphabetically? Is the script being run with lua5.1 or lua5.2?

Anyway, I changed the clear command to a simple 'rm'. Does that work?

``` xml
<openbox_pipe_menu>
  <item label='Clear recent files'>
    <command>&quot;rm&quot; &quot;/home/joj/.local/share/recently-used.xbel&quot;</command>
  </item>
  <separator/>
  <item label='x240__ug__en.pdf'>
    <action name='Execute'>
      <command>&quot;firefox&quot; &quot;file:///tmp/x240_ug_en.pdf&quot;</command>
    </action>
  </item>
</openbox_pipe_menu>
```

**Comment by capn-damo** [comment]
@johnraff 
For "Clear recent files" at the top of the menu, you should have:
`if xbel_path then`
   `add_remove_file_item(M, xbel_path)`
    `add_items_from_xbel(M, xbel_path, reverse, cnt, override)`
  `end`

@2ion 
`rm` doesn't work for me

**Comment by ghost** [comment]
What's the corrrect format for the <command> tag's contents to be in when it needs to be quoted?

```
'rm $path'
'rm' '$path' <-- currently
```

I think it's a quoting issue.

**Comment by capn-damo** [comment]
The pipemenu tag doesn't need quotes, as it appears in the menu (after variable expansion):
`<command>rm /home/joj/.local/share/recently-used.xbel</command>`.

Unless it is more complex, like:
`<command>x-terminal-emulator -T 'htop task manager' -e htop</command>`

or
`<command>zenity --text-info --title=&quot;How to Edit the Menu&quot; --filename=&quot;/usr/share/bunsen/bunsen-docs/helpfile-menu.txt&quot; --width=900 --height=700</command>`

**Comment by johnraff** [comment]
I must have been dreaming or something...
Looked again today and "Clear recent files" is at the top of the menu.

However, it still doesn't work unfortunately.
I'm getting this at the top of the menu:
`<item label='Clear recent files'>
        <command>&quot;rm&quot; &quot;/home/john/.local/share/recently-used.xbel&quot;</command>
      </item>`

Ah - there are no `<action name='Execute'>...</action>` tags around the command.

I don't know lua, but by comparing with the other menu items I found:

```
  m:add_direct_child(
    mk_item_tag("Clear recent files", {
      mk_action_tag("Execute", mk_command_tag("rm", path))})
    )
```

ie adding { } curly brackets round the mk_action_tag fixed it for me.

**Comment by ghost** [comment]
Thanks. I hate XML.
