### ISSUE TITLE
Change some dependencies to recommends?

### ISSUE THREAD

**Issue by johnraff** [BunsenLabs/bunsen-pipemenus#36]
**bunsen-pipemenus** has a long list of dependencies: https://github.com/BunsenLabs/bunsen-pipemenus/blob/master/debian/control
including, for example _both_ wget and curl. (That looks like a case for rewriting one of the scripts to use, maybe, wget.)

I have already moved _compton_ from Depends: to Recommends: as only the bl-compositor menu would be affected by its absence.

Maybe there are some other packages that could be recommends? We don't want to force people to install a lot of unnecessary packages.

**Comment by Sector11** [comment]
I'm not a script writer but wouldn't (I found this on the net)

```
blah blah
read -p "wget will be installed do you want curl as well? (Y|n) " yn
case $yn in
[Yy]* ) some command;;
[Nn]* ) different command;;
script continues
```

slap me if I'm too far off course.

**Comment by johnraff** [comment]
That's the basic point, yes.
wget and curl do similar jobs, but their syntax is different so a script that used curl would have to be tweaked a bit to use wget instead.

Each of them is good, and I have both because one is usually _easier to use_ than the other for some particular job.

Anyway, I'll do a `grep -r` and see what I can find.

**Comment by johnraff** [comment]
I can't find any script in bunsen-pipemenus which uses curl. Is there any other reason it would be needed?

**Comment by ghost** [comment]
I don't think so; I checked the curl package and the curl binary is the only one in the package. If no package uses curl, the dep can go.

**Comment by hhhorb** [comment]
Something's pulling xscreensaver, I can't remember what. I'd like that dropped so we can switch to light-locker, unless we want both installed.

**Comment by Sector11** [comment]
```
 18 Aug 15 | 07:51:42 ~
    $ rdep xscreensaver
alias apt-cache rdepends filename
xscreensaver
Reverse Depends:
  bunsen-utilities
  bunsen-utilities
  xscreensaver-gl-extra:i386
  xscreensaver-gl:i386
  xscreensaver-data-extra:i386
  xscreensaver-data-extra:i386
  xscreensaver-data:i386
  xscreensaver-data:i386
  xscreensaver:i386
  xscreensaver-gl-extra
  xscreensaver-gl-extra
  xscreensaver-gl
  xscreensaver-gl
  xscreensaver-data-extra
  xscreensaver-data-extra
  xscreensaver-data-extra
  xscreensaver-data
  xscreensaver-data
  xscreensaver-data
  xfce4-session
  xautolock
 |unicode-screensaver
 |rss-glx
  lxde-core
  kscreensaver-xsavers
  icewm-common
 |hibernate
  goban-ss
  gkrellshoot
  fvwm-crystal
  cwm
  blueproximity
  afterstep
 |acpi-support

 18 Aug 15 | 08:05:12 ~
    $ 
```

hibernate maybe?

**Comment by johnraff** [comment]
> Something's pulling xscreensaver

It's a dependency of **bunsen-utilities**. If we switch to light-locker then _bl-lock_ will be rewritten and the dependency will also be changed to light-locker.

**Comment by johnraff** [comment]
Anyway I've taken curl out of bunsen-pipemenus' dependencies.
