### ISSUE TITLE
bl-multimedia-pipemenu: change labelling of smplayer as "Gnome mplayer"

### ISSUE THREAD

**Issue by johnraff** [BunsenLabs/bunsen-pipemenus#37]
In the multimedia menu the entry for smplayer is changed to read "Gnome mplayer", while there is another different package gnome-mplayer. 

Change that entry back to Smplayer and add gnome-mplayer (also a reasonable alternative) to skel/.config/openbox/pipemenus.rc in bunsen-configs?

**Comment by capn-damo** [comment]
IIRC I did it that way to show that smplayer is the gui for mplayer. No problem if you change it to saner entries :)

**Comment by hhhorb** [comment]
Smplayer (Qt4) and Gnome-mplayer (Gtk) are GUIs for mplayer and mplayer2. Smplayer has worked well for me.

Gnome-mplayer2 has not, with either mplayer or mplayer2. The issue has been the same on 3 different computers, when switching to full-screen mode, the video continues playing for a second or two and then the screen goes black, though sound continues to work. Changing the video output or switching back to windowed mode have no effect, so this player has been useless to me. A shame, as I like it's simple interface.

mplayer2 is no longer maintained, AFAICT...
http://www.phoronix.com/scan.php?page=news_item&px=MTU1NzU

I thought mplayer was dead too, but apparently not...
http://mplayerhq.hu/design7/news.html

I haven't put either into the builds yet, let me know what I should do.

**Comment by hhhorb** [comment]
Sorry, multitasking here. I remembered that I don't need to do anything with the ISO, this is just about the menu and it's "Install" options.

**Comment by johnraff** [comment]
So:
- Take out the special treatment for smplayer, so it just appears as "Smplayer" or something.
- Add gnome-mplayer to the default list in pipemenus.rc.

OK?

> Gnome-mplayer2 ... the same on 3 different computers, when switching to full-screen mode, the video continues playing for a second or two and then the screen goes black, though sound continues to work.

I've just tried this with an mp4 video (downloaded from YouTube), on my Waldorf desktop and in a BL VB and could not reproduce that issue. Could it be related to the media type? Might it be an old bug that has been fixed? Could it be my particular (somewhat old) hardware?

**Comment by hhhorb** [comment]
I have no idea. As long as we're not installing mplayer and it's front-ends by default, it's fine by me.

And yes, the menu items should read SMPlayer and Gnome-MPlayer. I'm not booted into Hydrogen ATM, one minute...

**Comment by hhhorb** [comment]
Huh, the "Install Smplayer" is gone from the pipemenu in the new build. I see...
- Vlc
- Install Mpv
- Install Audacious
- Install Gnome mplayer

**Comment by johnraff** [comment]
> the "Install Smplayer" is gone from the pipemenu in the new build. I see...

That's what this issue is all about. The Good Captain renamed the smplayer entry to "Gnome mplayer"...

**Comment by hhhorb** [comment]
Got it, thanks! So yes to your issue... SMPlayer should be labeled SMPlayer, not Gnome-MPlayer.

**Comment by johnraff** [comment]
And damo said OK way back, so I'll go ahead and do it. Bruce or Jens, feel free to reopen if there's a problem with that.

**Comment by johnraff** [comment]
BTW @capn-damo hope it's OK but while doing the above I removed an unnecessary line and quoted two variables (just to get the output nicely formatted for someone who looks at it in a terminal). You can check the changes on GitHub.

**Comment by capn-damo** [comment]
Hey, you don't need to worry about correcting or polishing any of my code! Just go ahead an do it - you Da Man :)

**Comment by johnraff** [comment]
Jee...
