### ISSUE TITLE
bl-multimedia-pipemenu remove "volti" entry, do not add "volumeicon"?

### ISSUE THREAD

**Issue by johnraff** [BunsenLabs/bunsen-pipemenus#38]
Noticed this while looking at the media players thing. Is there any reason to have an entry in the multimedia menu to install or invoke a systray volume icon? Now volti's being replaced, shall I just take it out of the menu?

**Comment by capn-damo** [comment]
Yes. I can't recall why it was originally there!

**Comment by johnraff** [comment]
OK 
Actually it's in pipemenus.rc but anyway.
