### ISSUE TITLE
bl-dropbox-pipemenu doesn't show progress of dependency installation

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-pipemenus#39]
If python-gpgme is needed during Dropbox install, there is nothing to show any progress, so it seems that the script has stopped. Users may assume the install has failed, if they don't wait long enough.

Proposed fix: change

`gksu 'apt-get install -y python-gpgme' || {`

to

`x-terminal-emulator -T 'Install python-gpgme' -e sudo apt-get install -y python-gpgme || {`

**Comment by ghost** [comment]
…or just do a

```
notify-send 'Dropbox' 'Installation finished'
```

at the end of the script. It can't take too long after all.

**Comment by capn-damo** [comment]
There is already a notification when the install is complete.

The point is that there is nothing displayed while the installation of the dependencies is going on. What is a reasonable time to wait before thinking the script has failed? 3 or 4 secs may be OK, but 30+ secs on an old machine with a slow connection is not acceptable IMO.

**Comment by johnraff** [comment]
OK there are already functions safeInstall() and terminalCheck() available in the common file - it might be easy to put something together. I'll have a look.

> It can't take too long after all.

That's what I thought to be honest - it's one small package, and I never noticed any appreciable delay, but if damo did then some other users will probably feel uncomfortable too.

**Comment by capn-damo** [comment]
`python-gpgme` also pulls in several other libs btw.

**Comment by johnraff** [comment]
Guess it depends on the state of your system beforehand. When I tried it I don't remember other stuff coming with it. Was it a lot of bytes?

For a while I was wondering if the install section of the script should be rewritten to run in a terminal like the other install pipemenus, but the zenity and notify-send stuff is so built in it feels like a shame to undo all that work. (By Philip I guess.)

Anyway @capn-damo your suggestion looks good. I might try exporting the safeInstall function to the terminal though.

**Comment by johnraff** [comment]
Getting stuck because I haven't been able to find any way to test the return value of a command run in a terminal launched as a _child_ of a script.

Any suggestions? The script will need to know if the installation of python-gpgme succeeded before continuing.

Otherwise it might have to be back to `gksu`, and just put up a "please wait" note or something.

**Comment by johnraff** [comment]
Fixed in bunsen-pipemenus (8.6.3-1) 
python-gpg is installed in a terminal window.
