### ISSUE TITLE
bl-compositor: needs to deal with '-h/--help' parameters

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-pipemenus#47]
We need a test for these commandline parameters, which may be a common action. ATM they cause the openbox menu to be output.

I suggest that it should display a link to the config file, `$HOME/.config/compton.conf`.

**Comment by johnraff** [comment]
In fact we ought to check all the executables in bunsen-utilities and make sure they have some kind of help message, since they're all meant to be directly available to users.

**Comment by ghost** [comment]
Consider using Python's argparse for consistent argument handling in all Python scripts (also helps with providing help text), and the getopt tool for handling -s(hort) and --long options in shell scripts (or the getopts Bash builtin for handling only short options). No more self-baked if-else trees if not otherwise required:

``` python
import argparse
 ap = ArgumentParser(description="NIBL package search CLI")
    ap.add_argument("-A", "--attrs", default=[], choices=["bold","underline","dark","blink","reverse","concealed"], action="append", help="Highlight attribute to use with -C.")
    ap.add_argument("-C", "--color", default=False, action="store_true", help="Highlight search term matches.")
    ap.add_argument("-H", "--highlight", default="yellow", choices=["grey","white","blue","green","red","yellow","cyan"], help="Highlight color to use with -C.")
    ap.add_argument("-a", "--age", type=int, default=3600, help="Maximum cache age in seconds. Defaults to 3600. Set to -1 in order to flush the cache.")
    ap.add_argument("-b", "--bot", metavar="BOT", default=[], action="append", help="Search BOT or all bots ('@'). Defaults to '@'. Specify multiple times to query results for more bots in parallel.")
    ap.add_argument("-c", "--cache", help="Cache file to use. Defaults to $HOME/.nibl.botlist.txt.")
    ap.add_argument("-l", "--list", default=False, action="store_true", help="List known bots.")
    ap.add_argument("-o", "--on", default=None, choices=["on_grey", "on_red", "on_green", "on_yellow", "on_blue", "on_magenta", "on_cyan", "on_white"], help="Background color to use with -H.")
    ap.add_argument("-r", "--reverse", action="store_true", default=False, help="If --sort has been given, revert to descending sort order.")
    ap.add_argument("-s", "--sort", metavar="COLUMN", default=None, help="Sort by either botname, packnumber, filesize, or filename.")
    ap.add_argument("-w", "--wrap", default=False, action="store_true", help="Wrap long lines at terminal border.")
    ap.add_argument("query", metavar="TERM", nargs="*", help="Search term. All positional arguments are concatenated.")
    args = ap.parse_args()
```

If you write Lua, you should use posix.getopt from lua-posix.

``` lua
for o, optarg, opterr in posix.getopt(arg, "hf:l:o:r", {
    { "limit",    "required", 'l' },
    { "help",     "none",     'h' },
    { "file",     "required", 'f' },
    { "reverse",  "none",     'r' },
    { "open-cmd", "required", 'o' }}) do
```

Same for Ruby, etc.

**Comment by johnraff** [comment]
Python and the other more sophisticated languages clearly have built-in argument handling that we should be using wherever possible IMO.

As for getopt and getopts with shell scripts - they are tricky to use and each of them has disadvantages: getopt cannot handle "squashed" options like -abc, and getopts cannot handle long options like --help. The [Bash Wiki](http://mywiki.wooledge.org/BashFAQ/035) says: 

> Manually parsing options without the use of a specialized function is the most flexible approach, and is sufficient for most simple scripts

and later (about getopts)

> There is also still the disadvantage that options are coded in at least 2, probably 3 places - in the call to getopts, in the case statement that processes them and presumably in the help message that you are going to get around to writing one of these days. This is a classic opportunity for errors to creep in as the code is written and maintained - often not discovered till much, much later.

Would there be something to be said for making an _args2array_ function in the shared bl-include.cfg file, that would cleanly read in args and options and put them in an associative array for use by the script?

**Comment by ghost** [comment]
Custom parsing breaks interfacing expectations. I.e.

```
program --option -o 2 -- --option
```

should not treat the last --option as such but as a positional argument, as well as --option=argument forms should be accepted as implemented by the getopt(3) function.

The point about getopt(1) limitations is not true; it supports squashed options just fine and will in general eat about everything that getopt_long(3) would. Here is some example usage: https://github.com/2ion/playtime/blob/master/playtime#L174. A bit verbose, but the style is roughly consistent what one would do in C: https://github.com/2ion/crctk/blob/master/src/crctk.c#L96 https://github.com/2ion/forecast/blob/master/src/forecast.c#L161.

Strictly speaking, Python also has a getopt module though argparse is nice in that it also generates the helptext https://docs.python.org/3.1/library/getopt.html.

**Comment by ghost** [comment]
I should add that I like the idea of having an option parser, wrapped in a library, that does the associative array magic. It should error out though if an option is malformed or not accepted by that particular program, i.e. it should accept a list of permitted options, and would also need to decide if an option takes a subsequent argument. Perhaps like so:

``` sh
bl_parse_opts 'SHORTFORM:LONGFORM:TYPEOFARGUMENT:HELPTEXT' 'option2'
bl_parse_opts 'h:help::Prints a summary of supported options'
bl_parse_opts 'c:config:FILE:Path to the configuration file' # also checks if the argument is an existing file
bl_parse_opts 'x:command:EXECUTABLE:Path to the executable to run' # also checks if the argument is an existing executable file
bl_parse_opts 'd:output-dir:DIR:Output directory path' # checks if the argument is a writable directory'
bl_parse_opts 'd:output-dir:MKDIR:Output directory path' # checks if the argument is a writable directory, if it not exists, tries to create it'
bl_parse_opts 'd:output-dir:REQ|DIR:Output directory path' # This option is REQUIRED!
bl_parse_opts 'd:output-dir:REQ|MKDIR:Output directory path' # This option is also REQUIRED, with the behaviour as described above'
```

We could even use getopt(1) internally to parse the command line, as the required information to use it can be derived from bl_parse_opts arguments.

I can draft an implementation tonight. Would make a neat project.

**Comment by johnraff** [comment]
> Custom parsing breaks interfacing expectations.

Agreed, although for a simple script that takes no arguments and only a couple of options like -h|--help, -v|--verbose, sophisticated parsing might be overkill.

> We could even use getopt(1) internally to parse the command line, as the required information to use it can be derived from bl_parse_opts arguments.
> 
> I can draft an implementation tonight. Would make a neat project.

That sounds nice!

**Comment by ghost** [comment]
It's only overkill if you have to write 100 lines of boilerplate every time. So let's try the library function route.

**Comment by johnraff** [comment]
^sounds good.

**Comment by johnraff** [comment]
> The point about getopt(1) limitations is not true; it supports squashed options just fine

Indeed, tested and confirmed - at least with the version of getopt that we have in Debian Jessie.

```
bl_parse_opts 'h:help::Prints a summary of supported options'
bl_parse_opts 'c:config:FILE:Path to the configuration file'
```

So, this envisages passing all the options to bl_parse_opts as a series of single-quoted words? Like:

```
bl_parse_opts 'h:help::Prints a summary of supported options' 'c:config:FILE:Path to the configuration file'
```

Perhaps putting the option configurations in an array might be more robust? Like:

```
bl_opts_array=(h:help::Prints a summary of supported options)
bl_opts_array+=(c:config:FILE:Path to the configuration file)
```

> I can draft an implementation tonight. Would make a neat project.

Any progress here?

**Comment by ghost** [comment]
> Any progress here?

No.

**Comment by johnraff** [comment]
@capn-damo @2ion 
I played with an experimental bash implementation yesterday (a function to source in the calling script). While it looked doable, it isn't simple at all if you want to cover _all_ the possibilities while keeping the default code in the calling script as simple as possible. I'm sure @2ion could come up with something better, but if it's a python or lua executable then we will no longer be able to _share_ variables as a sourced shell function can.

Deuterium will presumably be out in September or so.
For now, shall we add a simple test for -h|--help to all the scripts we install to /usr/bin, if there isn't one at the moment?

> I suggest that it should display a link to the config file, $HOME/.config/compton.conf.

You mean have such a link displayed in the help text? If so, agreed. I don't think most users would expect '--help' to do anything except output a text message.

**Comment by capn-damo** [comment]
@johnraff 

I think the easiest solution atm is to add a simple test, and display where the appropriate help can be found, eg a link to the config file, manpages, etc

**Comment by johnraff** [comment]
@capn-damo that, along with a list of the options, if there are any.
bl-compositor is already going over various options, so until option handling is completely redone, it would be just a question of adding one more.

EDIT OTOH many of the pipemenus have no options at all - they just run, and are not expected to be run directly by users, but called in an openbox menu. But I suppose out of principle anything in /usr/bin should have a --help option, and even a manpage really.

**Comment by johnraff** [comment]
Should we exit out with an error message if an invalid argument is passed, instead of just outputting the menu?

**Comment by johnraff** [comment]
In fact, bl-compositor has several options; how about something like this at the top of the script? Everything else can remain as-is.

```
HELP='    bl-compositor an Openbox Pipe Menu for use with compton compositor
    It should normally be called from an openbox menu.

Options (usually passed from the menu):
    -h --help   show this message
    --start     start the compositor and restart tint2, if running
    --restart   restart the compositor, if running, and restart tint2
    --stop      stop the compositor
    --edit      open the compton config file in a text editor
    --watch     restart the compositor whenever the config file is modified
    (--watch is useful for debugging)

See ~/.config/compton.conf and "man compton" for configuration options.
'
# look for a help option somewhere
while [[ $1 ]]
do
    case "$1" in
    -h|--help)
        echo "$HELP"
        exit 0
        ;;
    esac
    shift
done
```

**Comment by capn-damo** [comment]
That looks really good :)

**Comment by johnraff** [comment]
Sorry, that bit of code that checks the options for "--help" would have broken the later parts of the script - the `shift` would delete them all!
This should leave the parameters (options) intact:

```
# look for a help option somewhere
for i in "$@"
do
    case "$i" in
    -h|--help)
        echo "$HELP"
        exit 0
        ;;
    esac
done
```

Anyway, if that kind of help message looks OK I'll go ahead and put something similar in the other scripts (in Deuterium). Of course in many cases there will be very little to say beyond "just let it do its thing".

EDIT that pesky `shift` was still there - now removed.

**Comment by johnraff** [comment]
A $HELP text and -h|--help options have now been added to all the shell script pipemenus in _bunsen-pipemenus_ in deuterium. Especially @capn-damo please feel free to edit any help texts to taste.

bl-sshconfig-pipemenu is a python script; if any python coder would like to add a --help option there?

**Comment by xaosfiftytwo** [comment]
> bl-sshconfig-pipemenu is a python script; if any python coder would like to add a --help option there?

Done

**Comment by johnraff** [comment]
Thanks!
