### ISSUE TITLE
bl-x-www-browser-pipemenu: select default browser should exit with a message...

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-pipemenus#49]
...if only one browser is installed. 

When running the command in a terminal:

```
sudo update-alternatives --config x-www-browser
[sudo] password for user: 
There is only one alternative in link group x-www-browser (providing /usr/bin/x-www-browser): /usr/bin/firefox-esr
Nothing to configure.
```

If run from the menu item, the screen just exits without informing the user there is nothing to configure. So causing confusion to a new user, who may think there is a bug! https://forums.bunsenlabs.org/viewtopic.php?id=2867

**Comment by johnraff** [comment]
The easiest fix is to put in a delay before closing the terminal:

```
menuItem 'Select Default Browser' "x-terminal-emulator -T 'Select Default Browser' -e sh -c 'sudo update-alternatives --config x-www-browser; sleep 6'"
```

But an alternative would be to make $INSTALLED an integer, increment it each time an installed browser is found, and check if it's greater than one before displaying the menu item.

**Comment by johnraff** [comment]
That second alternative mentioned above would miss browsers installed by some other route. For now, let's just add the 6 sec sleep.

Now done in deuterium branch. (sleep dropped to 5 sec)
