### ISSUE TITLE
bl-x-www-browser-pipemenu: there is no package called "firefox" in Debian Jessie

### ISSUE THREAD

**Issue by johnraff** [BunsenLabs/bunsen-pipemenus#50]
*bl-x-www-browser-pipemenu* will attempt to install "firefox" if called from the menu, which will fail because Debian Jessie offers only "firefox-esr". (Since firefox is installed by default this will affect only a few users.)

Fix:
1) Edit ~/.config/openbox/pipemenus.rc to refer to 'firefox-esr', and edit bl-x-www-browser-pipemenu to display the app name as "Firefox" not "Firefox Esr".

**or**

2) Edit bl-x-www-browser-pipemenu to install 'firefox-esr' when asked to install 'firefox'.

(2) requires editing one file only, but (1) keeps the integrity of the package list in pipemenus.rc as referring to packages that exist!

Opinions?

**Comment by ghost** [comment]
I'd vote for (2) because it fixes the problem on existing installs too.

**Comment by johnraff** [comment]
Alternative (2) implemented in deuterium branch with commit 4b5c5db
